package com.wellsfargo.counselor.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

/**
 * Represents a security entity in the portfolio management system.
 * This class maps to a database table using JPA (Jakarta Persistence API) annotations.
 */
@Entity
public class Security {

    /**
     * The unique identifier for each security.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue
    private long securityId;

    /**
     * The name of the security.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The category of the security.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String category;

    /**
     * The date on which the security was purchased.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String purchaseDate;

    /**
     * The purchase price of the security.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String purchasePrice;

    /**
     * The quantity of the security.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private int quantity;

    /**
     * Default constructor required by JPA.
     */
    public Security() {
    }

    /**
     * Parameterized constructor to initialize a Security object with specific values.
     *
     * @param securityId    The unique identifier for the security.
     * @param name          The name of the security.
     * @param category      The category of the security.
     * @param purchaseDate  The date on which the security was purchased.
     * @param purchasePrice The purchase price of the security.
     * @param quantity      The quantity of the security.
     */
    public Security(long securityId, String name, String category, String purchaseDate, String purchasePrice, int quantity) {
        this.securityId = securityId;
        this.name = name;
        this.category = category;
        this.purchaseDate = purchaseDate;
        this.purchasePrice = purchasePrice;
        this.quantity = quantity;
    }

    /**
     * Gets the unique identifier for the security.
     *
     * @return The unique identifier of the security.
     */
    public long getSecurityId() {
        return securityId;
    }

    /**
     * Sets the unique identifier for the security.
     *
     * @param securityId The unique identifier to set.
     */
    public void setSecurityId(long securityId) {
        this.securityId = securityId;
    }

    /**
     * Gets the name of the security.
     *
     * @return The name of the security.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the security.
     *
     * @param name The name to set.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the category of the security.
     *
     * @return The category of the security.
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the category of the security.
     *
     * @param category The category to set.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Gets the purchase date of the security.
     *
     * @return The purchase date of the security.
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the purchase date of the security.
     *
     * @param purchaseDate The purchase date to set.
     */
    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * Gets the purchase price of the security.
     *
     * @return The purchase price of the security.
     */
    public String getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * Sets the purchase price of the security.
     *
     * @param purchasePrice The purchase price to set.
     */
    public void setPurchasePrice(String purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * Gets the quantity of the security.
     *
     * @return The quantity of the security.
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the quantity of the security.
     *
     * @param quantity The quantity to set.
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
